### ISSUE TITLE
.gitignore license files

### ISSUE THREAD

**Issue by Hossman333** [Xaeroxe/nitro-game-engine#7]

**Comment by Hossman333** [comment]
And whatever else you need to ignore :D I would make PR, but #lazy. lol

**Comment by Xaeroxe** [comment]
Yeah this started getting copied over by the Windows build script and I never took the time to determine if we need to be redistributing these license files or not so I just left them there.  I'll figure out what's necessary with that though.

**Comment by Xaeroxe** [comment]
Could you rename this issue though?  S*** is a word some might find offensive, change it to files.

**Comment by Xaeroxe** [comment]
Fixed by https://github.com/Xaeroxe/nitro-game-engine/commit/bd6c59cfba154dfa68573ff0748aaeb12600fb87
